In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd 'drive/MyDrive/crypto-classifier/data'
!ls

Mounted at /content/drive
/content/drive/MyDrive/crypto-classifier/data
120_influ_total.json		       influencers_tweet_date_and_number.gsheet
2000_crypto_sample.csv		       lunarcrush_influencers
20coin_MC_lunarCrush_30days.csv        models
20coin_MC_lunarCrush_60days.csv        new_sell.csv
all_tweets.v2.csv		       new_tag
cardiffnlp			       old
cleaned_dataset.csv		       predict_crypto_keyword_2000.csv
cleaned_dataset.pickle		       predict_crypto_keyword_2000.xlsx
cleaned_dataset_sell.pickle	       reddit_data.csv
cleanTweet_800.csv		       relevant_crypto_TfidfVectorizer
coinList_100.csv		       Relevant_model
coin_name.csv			       result_data.zip
crypto_augmented_features_relevant     sample_reddit_3000.v1.csv
crypto_augmented_features_signal       tagged_tweets_v0.1.csv
crypto_keyword_total.csv	       targetdir
crypto_signal_model		       Top_100_coinMarketCap.csv
data_with_sell_keyword300.csv	       top_MCcoin_15.csv
hole_crowled146.csv		       voting200.v1.csv
influencers_tweet_date_and_number.csv  voting200.v1.gsheet

In [ ]:
'lunarcrush_influencers'

In [ ]:
!pip install lunarcrush

Collecting lunarcrush
  Downloading lunarcrush-1.0.1-py3-none-any.whl (6.7 kB)
Installing collected packages: lunarcrush
Successfully installed lunarcrush-1.0.1

In [ ]:
from lunarcrush import LunarCrush
import pandas as pd
from pprint import pprint
import json

In [ ]:
coins=pd.read_csv('top_MCcoin_15.csv')

In [ ]:
coins

   symbol  Unnamed: 1  Unnamed: 2
0     BTC         NaN         NaN
1     ETH         NaN         NaN
2    USDT         NaN         NaN
3     BNB         NaN         NaN
4    USDC         NaN         NaN
5     XRP         NaN         NaN
6     SOL         NaN         NaN
7     ADA         NaN         NaN
8    LUNA         NaN         NaN
9     UST         NaN         NaN
10   BUSD         NaN         NaN
11   DOGE         NaN         NaN
12   AVAX         NaN         NaN
13    DOT         NaN         NaN
14   SHIB         NaN         NaN

In [ ]:
lc = LunarCrush()
for csymbol in coins['symbol']:
  twitter_influencers=lc.get_influencers(symbol=[csymbol],days=60)
  with open(f'lunarcrush_influencers/data60_{csymbol}.json', 'w') as fp:
    json.dump(twitter_influencers, fp)

In [ ]:
import json
mdf=pd.DataFrame()
for csymbol in coins['symbol']:
  x = json.load(open(f'lunarcrush_influencers/data60_{csymbol}.json'))

  try:
    df=pd.DataFrame(x['data'])
    df['coin_name']=[csymbol]*(len(df))
    mdf=pd.concat([mdf,df],ignore_index=True)
  except:
    print(csymbol)
mdf

BTC
ETH

,medium,identifier,volume,followers,engagement,verified,twitter_screen_name,display_name,following,profile_image,banner_image,volume_rank,followers_rank,engagement_rank,influencer_rank_average,influencer_rank,coin_name
0,twitter,999947328621395968,28,1700627,12713,1,Bybit_Official,BYBIT 🦍,535,https://pbs.twimg.com/profile_images/147853817...,https://pbs.twimg.com/profile_banners/99994732...,36,7,5,17.666667,None,USDT
1,twitter,912539725071777792,55,833693,7904,0,gate_io,Gate.io,2632,https://pbs.twimg.com/profile_images/147862443...,https://pbs.twimg.com/profile_banners/91253972...,21,17,15,22.666667,None,USDT
2,twitter,1098881129057112064,65,347255,16582,1,bitgetglobal,Bitget,370,https://pbs.twimg.com/profile_images/148663259...,https://pbs.twimg.com/profile_banners/10988811...,19,51,2,24.666667,None,USDT
3,twitter,978184299122892800,130,373267,9708,0,BitrueOfficial,Bitrue,2157,https://pbs.twimg.com/profile_images/147901701...,https://pbs.twimg.com/profile_banners/97818429...,9,47,11,26.000000,None,USDT
4,twitter,910110294625492992,15,1781244,27256,1,kucoincom,KUCOIN,950,https://pbs.twimg.com/profile_images/150974331...,https://pbs.twimg.com/profile_banners/91011029...,76,6,1,28.000000,None,USDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1246,twitter,1517778977913331715,6,3947,13810,0,cawryoshi,A Hunters Dream $CAW,51,https://pbs.twimg.com/profile_images/151777919...,https://pbs.twimg.com/profile_banners/15177789...,1560,1975,70,1225.000000,None,SHIB
1247,twitter,1512283042835943433,138,968,18503,0,WahabApon,Shib Fans,1538,https://pbs.twimg.com/profile_images/151339049...,https://pbs.twimg.com/profile_banners/15122830...,96,3909,54,1371.000000,None,SHIB
1248,twitter,95023423,2,13672665,15018,1,UberFacts,UberFacts,1,https://pbs.twimg.com/profile_images/134016552...,https://pbs.twimg.com/profile_banners/95023423...,4331,1,67,1488.666667,None,SHIB
1249,twitter,1485018401642717186,2,18988,14411,0,ShibTheMV,SHIB: The Metaverse,2,https://pbs.twimg.com/profile_images/149893828...,https://pbs.twimg.com/profile_banners/14850184...,4216,842,69,1732.000000,None,SHIB
1250,twitter,1501566869005811715,2,20144,8690,0,LVNFTs,LVNFTS,53,https://pbs.twimg.com/profile_images/150883054...,None,4820,809,98,1941.666667,None,SHIB

In [ ]:
twitter_influencers=lc.get_influencers(symbol=['ETH'],days=60)
twitter_influencers

{'message': 'Service Unavailable'}

In [ ]:
mdf.to_csv('20coin_MC_lunarCrush_60days.csv')